# ================ LABELS
# Labels on which the network has been trained
labels_net: mscoco_label_map.json

# Labels to be used as output --> labels_net is remapped to labels_out
labels_out: kaist_label_map.json


# ================ DIRECTORIES
# The directory where the dataset files are stored as absolute path
dataset_dir: /shared_experiments/kaist/training/day

# Filter keywords that needs to be contained in the path
filter_keywords: []

# Name of the sub-directory containing images of the main sensor
main_sensor: visible

# Name of the sub-directory containing images of the auxiliary sensor
aux_sensor: lwir

# Name of the output dataset *.tfrecord
tfrecord_name_prefix: KAIST_TRAINING_DAY_rgb_050

# Additionally generated files during transfer_learning will be saved here
output_dir: /shared_experiments/kaist/results/datasets


# ================ GPUS MASK
# Passes argument to cuda visible devices, comma separated values
cuda_visible_devices: "1"


# ================ SEMI-SUPERVISED LABEL GENERATOR
# Passes argument to cuda visible devices, comma separated values
net_arch: 6

# Retrieval Threshold of the Detector used in generating the labels
retrieval_thresh: 0.5


# ================ PREPROCESSING
# Whether or not to normalize the images in the dataset to zero mean and unit variance
normalize: False

# Whether or not to normalize per single image or with stats from the whole dataset
per_image_normalization: True

# Determines the confidence interval for the image values, e.g. 3.0 leads to 99.7%
# of the values being kept for the scaling back procedure
confidence_interval: 3.0

# Whether or not to scale back images using cv2.normalize() method which will
# discard image mean and variance values. Otherwise normalized images are scaled
# back to range 0 to 255 using mean 127 and stddev derived from confidence_int
scale_back_using_cv2: False

# Min Object perimeter needed for learning filter. Set to 0 to turn it off
min_obj_size: 0

# Min Learning Filter Observability Score. Objects below will be discarded
# or flagged as difficult. Set to 0 to disable the learning filter
lf_score_thresh: 0
                     

# ================ VISUALIZATION AND PLOTS
# Activates verbose mode with visualisation
verbose: False

# Generates and saves plots on the home folder
generate_plots: True

# Wether or not to show generated plots. Put false if running through SSH
show_plots: False
